import { Doctor, Hospital, Service } from '@/types/booking';

export const mockDoctors: Doctor[] = [
    {
        id: '1',
        name: 'Dr. Nguyễn Văn Minh',
        avatar: '/src/assets/img/doctors/doctor-01.jpg',
        specialty: 'Bác sĩ Tim mạch',
        experience: 15,
        rating: 4.8,
        reviewCount: 127,
        location: 'Bệnh viện Bạch Mai',
        consultationFee: 400000,
        availableToday: true,
    },
    {
        id: '2',
        name: 'Dr. Trần Thị Lan',
        avatar: '/src/assets/img/doctors/doctor-02.jpg',
        specialty: 'Bác sĩ Nhi khoa',
        experience: 12,
        rating: 4.9,
        reviewCount: 203,
        location: 'Bệnh viện Nhi Trung ương',
        consultationFee: 325000,
        availableToday: true,
    },
    {
        id: '3',
        name: 'Dr. Lê Quang Hải',
        avatar: '/src/assets/img/doctors/doctor-03.jpg',
        specialty: 'Bác sĩ Thần kinh',
        experience: 18,
        rating: 4.7,
        reviewCount: 156,
        location: 'Bệnh viện Việt Đức',
        consultationFee: 500000,
        availableToday: false,
    },
    {
        id: '4',
        name: 'Dr. Phạm Thị Hương',
        avatar: '/src/assets/img/doctors/doctor-04.jpg',
        specialty: 'Bác sĩ Sản phụ khoa',
        experience: 20,
        rating: 4.8,
        reviewCount: 189,
        location: 'Bệnh viện Phụ sản Trung ương',
        consultationFee: 450000,
        availableToday: true,
    },
    {
        id: '5',
        name: 'Dr. Hoàng Văn Thành',
        avatar: '/src/assets/img/doctors/doctor-05.jpg',
        specialty: 'Bác sĩ Chấn thương chỉnh hình',
        experience: 10,
        rating: 4.6,
        reviewCount: 98,
        location: 'Bệnh viện Việt Đức',
        consultationFee: 400000,
        availableToday: false,
    },
];

export const mockHospitals: Hospital[] = [
    {
        id: '1',
        name: 'Bệnh viện Bạch Mai',
        logo: '/src/assets/img/clinic/clinic-10.jpg',
        address: '78 Giải Phóng, Đống Đa, Hà Nội',
        rating: 4.5,
        reviewCount: 1234,
        distance: '2.5 km',
        specialties: ['Tim mạch', 'Nội khoa', 'Ngoại khoa', 'Cấp cứu'],
        emergency: true,
    },
    {
        id: '2',
        name: 'Bệnh viện Việt Đức',
        logo: '/src/assets/img/clinic/clinic-10.jpg',
        address: '40 Tràng Thi, Hoàn Kiếm, Hà Nội',
        rating: 4.6,
        reviewCount: 987,
        distance: '1.2 km',
        specialties: ['Ngoại khoa', 'Chấn thương chỉnh hình', 'Thần kinh', 'Ung bướu'],
        emergency: true,
    },
    {
        id: '3',
        name: 'Bệnh viện Nhi Trung ương',
        logo: '/src/assets/img/clinic/clinic-10.jpg',
        address: '18/879 La Thành, Đống Đa, Hà Nội',
        rating: 4.7,
        reviewCount: 523,
        distance: '1.8 km',
        specialties: ['Nhi khoa', 'Sản phụ khoa', 'Tim mạch nhi'],
        emergency: true,
    },
    {
        id: '4',
        name: 'Bệnh viện Da liễu Trung ương',
        logo: '/src/assets/img/clinic/clinic-10.jpg',
        address: '15A Phương Mai, Đống Đa, Hà Nội',
        rating: 4.4,
        reviewCount: 387,
        distance: '2.3 km',
        specialties: ['Da liễu', 'Thẩm mỹ', 'Dị ứng'],
        emergency: false,
    },
    {
        id: '5',
        name: 'Bệnh viện Mắt Trung ương',
        logo: '/src/assets/img/clinic/clinic-11.jpg',
        address: '85 Bà Triệu, Hai Bà Trưng, Hà Nội',
        rating: 4.6,
        reviewCount: 298,
        distance: '3.5 km',
        specialties: ['Mắt', 'Phẫu thuật mắt', 'Khúc xạ'],
        emergency: false,
    },
    {
        id: '6',
        name: 'Bệnh viện Tai mũi họng Trung ương',
        logo: '/src/assets/img/clinic/clinic-12.jpg',
        address: '78 Giải Phóng, Đống Đa, Hà Nội',
        rating: 4.5,
        reviewCount: 412,
        distance: '2.7 km',
        specialties: ['Tai mũi họng', 'Phẫu thuật TMH', 'Thính học'],
        emergency: false,
    },
    {
        id: '7',
        name: 'Bệnh viện Tâm thần Trung ương',
        logo: '/src/assets/img/clinic/clinic-10.jpg',
        address: '78 Giải Phóng, Đống Đa, Hà Nội',
        rating: 4.3,
        reviewCount: 156,
        distance: '4.1 km',
        specialties: ['Tâm thần', 'Tâm lý', 'Nghiện chất'],
        emergency: true,
    },
];

export const mockServices: Service[] = [
    {
        id: '1',
        name: 'Khám thần kinh tổng hợp',
        description:
            'Khám và đánh giá toàn diện các vấn đề về thần kinh, bao gồm đau đầu, chóng mặt, rối loạn giấc ngủ',
        price: '200.000đ - 500.000đ',
        duration: '45 phút',
        category: 'Thần kinh',
        availability: 'Hôm nay',
    },
    {
        id: '2',
        name: 'Xét nghiệm máu tổng quát',
        description: 'Xét nghiệm máu cơ bản để kiểm tra tình trạng sức khỏe tổng quát',
        price: '150.000đ - 300.000đ',
        duration: '15 phút',
        category: 'Xét nghiệm',
        availability: 'Trong tuần',
    },
    {
        id: '3',
        name: 'Siêu âm tim',
        description: 'Siêu âm tim để kiểm tra chức năng tim và phát hiện các bệnh lý tim mạch',
        price: '300.000đ - 600.000đ',
        duration: '30 phút',
        category: 'Tim mạch',
        availability: 'Hôm nay',
    },
    {
        id: '4',
        name: 'Nội soi dạ dày',
        description: 'Nội soi dạ dày để chẩn đoán các bệnh lý đường tiêu hóa',
        price: '800.000đ - 1.200.000đ',
        duration: '60 phút',
        category: 'Tiêu hóa',
        availability: 'Trong tuần',
    },
    {
        id: '5',
        name: 'Chụp X-quang ngực',
        description: 'Chụp X-quang ngực để kiểm tra phổi và tim',
        price: '100.000đ - 200.000đ',
        duration: '10 phút',
        category: 'Chẩn đoán hình ảnh',
        availability: 'Hôm nay',
    },
    {
        id: '6',
        name: 'Khám mắt tổng quát',
        description: 'Khám mắt toàn diện bao gồm đo thị lực và kiểm tra các bệnh lý mắt',
        price: '250.000đ - 400.000đ',
        duration: '30 phút',
        category: 'Mắt',
        availability: 'Hôm nay',
    },
    {
        id: '7',
        name: 'Khám phụ khoa',
        description: 'Khám phụ khoa định kỳ và tư vấn sức khỏe sinh sản',
        price: '200.000đ - 350.000đ',
        duration: '30 phút',
        category: 'Sản phụ khoa',
        availability: 'Trong tuần',
    },
    {
        id: '8',
        name: 'Khám da liễu',
        description: 'Khám và điều trị các bệnh lý về da, tóc, móng',
        price: '150.000đ - 300.000đ',
        duration: '20 phút',
        category: 'Da liễu',
        availability: 'Hôm nay',
    },
    {
        id: '9',
        name: 'Khám tai mũi họng',
        description: 'Khám tai mũi họng để phát hiện các bệnh lý về đường hô hấp',
        price: '180.000đ - 320.000đ',
        duration: '25 phút',
        category: 'Tai mũi họng',
        availability: 'Hôm nay',
    },
    {
        id: '10',
        name: 'Tư vấn tâm lý',
        description: 'Tư vấn tâm lý và hỗ trợ điều trị các vấn đề tâm lý',
        price: '400.000đ - 800.000đ',
        duration: '50 phút',
        category: 'Tâm lý',
        availability: 'Trong tuần',
    },
];
